Menu ppl
El-limon-mecanico/TheHallway pull request #3
Opened 2021-05-19 17:26 UTC by Agusmoure

2021-05-19 18:28 UTC, anmartan commented on TheHallwaySol/Assets/lua/Scenes/MenuCtrl.lua
> +}
Cuando clico en cualquier sitio en esta escena (menos en el botón), el botón desaparece, y ya no puedo salir.

2021-05-19 18:28 UTC, anmartan requested changes
Problemas con el menú de controles

2021-05-19 18:58 UTC, Agusmoure commented on TheHallwaySol/Assets/lua/Scenes/MenuCtrl.lua
> +}
Listo el problema venia del motor al hacer el update del submodule se arregla

2021-05-21 07:31 UTC, anmartan approved these changes

2021-05-21 07:43 UTC, merged